package br.com.bank.enumeration;

import lombok.Getter;

@Getter
public enum SchoolingEnum {

    FUNDAMENTAL_COMPLETO,
    FUNDAMENTAL_CURSANDO,
    MEDIO_COMPLETO,
    MEDIO_CURSANDO,
    SUPERIOR_COMPLETO,
    SUPERIOR_CURSANDO,
    POS_GRADUACAO_COMPLETO,
    POS_GRADUACAO_CURSANDO,
    MESTRADO_COMPLETO,
    MESTRADO_CURSANDO,
    DOUTORADO_COMPLETO,
    DOUTORADO_CURSANDO;
}
